baseURL = "https://prodrone.kr"
languageCode = "ko-KR"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
title = "proDRONE.kr"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[author]
  name = "ProDrone"

[params]
  description = "드론/카메라 최신 뉴스"
  defaultTheme = "auto"

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  responsive = true
  linkFullImages = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "홈"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "소개"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "문의"
    url = "/contact/"
    weight = 3
  [[menu.main]]
    name = "개인정보처리방침"
    url = "/privacy/"
    weight = 4
  [[menu.main]]
    name = "이용약관"
    url = "/terms/"
    weight = 5
