baseURL = "https://prodrone.kr"
languageCode = "ko-KR"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
title = "ProDrone.kr"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[author]
  name = "ProDrone"

[params]
  description = "드론/카메라 최신 뉴스"
  defaultTheme = "auto"
  cover.responsive = true
  cover.linkFullImages = true
  summary = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "홈"
    url = "/"
    weight = 1
